name: Push

on: push

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Create deployment
        id: deployment
        uses: octokit/request-action@v2.x
        with:
          route: POST /repos/:repository/deployments
          # mediaType: |
          #   previews:
          #     - ant-man
          repository: ${{ github.repository }}
          ref: ${{ github.sha }}
          environment: test
          # transient_environment: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - run: echo ${{ steps.deployment.outputs.data }}

      - name: Update Deployment
        if: always()
        uses: octokit/request-action@v2.x
        with:
          route: POST /repos/:repository/deployments/:deployment_id/statuses
          repository: ${{ github.repository }}
          deployment_id: ${{ fromJson(steps.deployment.outputs.data).id }}
          state: ${{ job.status }}
          environment_url: https://www.google.com
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
